postgresql:
  image: sameersbn/postgresql:9.4
  environment:
    - DB_USER=gitlab
    - DB_PASS=secretpassword
    - DB_NAME=gitlabhq_production
gitlab:
  image: sameersbn/gitlab:7.9.1
  environment:
    - GITLAB_HOST=192.168.3.136
    - GITLAB_PORT=10080
  links:
   - redis:redisio
   - postgresql:postgresql
  ports:
   - "10080:80"
   - "10022:22"
redis:
  image: sameersbn/redis:latest
